### ISSUE TITLE
What is the first parameter in ipc.server.on( 'data' ) callback?

### ISSUE THREAD

**Issue by SlavMFM** [RIAEvangelist/node-ipc#120]
Hello. I'm new to **node-ipc** and UDP. Trying to send UDP messages of length 32 bytes from **asio** (C++) client to such **node-ipc** server:
```javascript
ipc.config.rawBuffer = true
ipc.config.encoding = 'hex'
ipc.config.silent = true
ipc.serveNet(
    11000,
    'udp4',
    function()
    {
        ipc.server.on(
            'data',
            function( data, socket )
            {
                try
                {
                    console.log( 'socket:', socket, 'got a message:', data, 'hex:', data.toString( 'hex' ), 'length:', data.length )
                }
                catch ( e )
                {
                    console.error( 'Data processing failed: ', e )
                }
            }
        )
    }
)
ipc.server.start()
```

prints to console:

> socket: { address: '127.0.0.1', family: 'IPv4', port: 47340, size: 32 } got a message: \<Buffer \> hex:  length: 0

Why data.length is 0 and, it's not a coincidence (checked with other data being sent), socket.size is 32?
How can I read received data?

Thanks in advance.

**Comment by RIAEvangelist** [comment]
You are receiving an empty buffer.

What are you sending?




On Jun 12, 2017 8:08 AM, "Slaus Blinnikov" <notifications@github.com> wrote:

Hello. I'm new to both node-ipc and UDP. Trying to send UDP messages of
length 32 bytes from asio (C++) client to such node-ipc server:
ipc.config.rawBuffer = true ipc.config.encoding = 'hex' ipc.config.silent =
true ipc.serveNet( 11000, 'udp4', function() { ipc.server.on( 'data',
function( data, socket ) { try { console.log( 'socket:', socket, 'got a
message:', data, 'hex:', data.toString( 'hex' ), 'length:', data.length ) }
catch ( e ) { console.error( 'Data processing failed: ', e ) } } ); } )
ipc.server.start()

prints to console:

socket: { address: '127.0.0.1', family: 'IPv4', port: 47340, size: 32 } got
a message: hex: length: 0

Why data.length is 0 and, it's not a coincidence (checked with other data
being sent), socket.size is 32?

Thanks in advance.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/RIAEvangelist/node-ipc/issues/120>, or mute the thread

**Comment by SlavMFM** [comment]
Sending code on C++ side:
```c++
    int array[] = { 1, 2, 3, 4, 5, 6, 7, 8 };
    s->send_to(
        asio::buffer(
            array,
            sizeof( int ) * 8
        ),
        endpoint
    );
```
That is modified version of my actual code where I was sending data of size 8 and on node.js side data.length was also 0 but socket.size was equal 8

**Comment by RIAEvangelist** [comment]
whatever ended up happening here?

**Comment by SlavMFM** [comment]
No, I just gave up on it and directly listened to UDP on Node server.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
