### ISSUE TITLE
[Question] Cross Platform usage

### ISSUE THREAD

**Issue by dushyantbangal** [RIAEvangelist/node-ipc#144]
I'm thinking about using local Unix Socket Server for connecting my different microservices.
With the examples, I'm easily able to connect the node.js based clients.

How can I use this with python clients? Is there any library that you can point me to or show me a way I can achieve this?

If I'm able to connect to the Socket, what kind of format do I have to use in order for the node-ipc to detect the event name and other things?

**Comment by RIAEvangelist** [comment]
If you still need this info, please let me know where you would expect it in the docs, if not already there.

Thanks

**Comment by Silve2611** [comment]
@RIAEvangelist I could not find it in the docs. I think the it would be best placed in the end of the docs in a cross-plattform section. One Example on Howto sendo a message from Python and also how to Receive a message if node-ipc sends one. 

The basic Problem is that one needs to know how the socket locks like to connect to it from any other language. It does not become clear from the docs. Usually it is host and port but node-ipc refuses a connection because something (host url incorrect) is missing.

**Comment by RIAEvangelist** [comment]
You just create a unique socket in python, send a json payload, and end each payload with the delimiter from your config in node IPC. The delimiter is used to parse when multiple messages come across the pipe back to back.

The default is backslash d.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
