### ISSUE TITLE
Request to update `event-pubsub`.

### ISSUE THREAD

**Issue by msyfls123** [RIAEvangelist/node-ipc#191]
https://github.com/RIAEvangelist/node-ipc/blob/50c0ec6735497c4dbeb2bfe7290b837dc1bf3aeb/package.json#L13

Please update `event-pubsub`, since 4.3.0 will not handle `*` correctly.

https://github.com/RIAEvangelist/event-pubsub/blob/v4.3.0/es5.js#L90-L105
`args` is possibly `undefined` and `type` is not applied to handler.

**Comment by matibat** [comment]
+1

In my case, my app crashes when the 'close' event is emmited

**Comment by RIAEvangelist** [comment]
+1 understood, but your app crashing is possibly not solely related to this
request.

**Comment by matibat** [comment]
@RIAEvangelist my app crashes when I set the '*' handler. When a client disconnects, the event is emitted like so: 
`emit$('close', false)`. It crashes because `args = false` and not `args = [ false ]` when later setting the `.shift()` function to it. `args` is supposed to be an array.

The emit function is defined like so:
`function emit$(type, args){`

But it should use argument unpacking, it must be replaced to
`function emit$(type, ...args){`
For it to work.

**Comment by RIAEvangelist** [comment]
interesting.

**Comment by RIAEvangelist** [comment]
duplicate #187

Will happen soon

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
