### ISSUE TITLE
The connected socket's "id" is never passed to the server

### ISSUE THREAD

**Issue by frzsombor** [RIAEvangelist/node-ipc#222]
I think the #175 is still an issue in the current version.

The 'id' of the server are always set on the side of the clients (in connect/connectNet), but the server never knows the 'id' of the connected client. Therefore `socket.id` will always be _undefined_ [here](https://github.com/RIAEvangelist/node-ipc/blob/10.1.0/dao/socketServer.js#L131) and will still result in logging _"client false has disconnected!"_ [here](https://github.com/RIAEvangelist/node-ipc/blob/10.1.0/README.md?plain=1#L555).

However until it's fixed, I managed to solve this by implementing a simple "introduction" between the server and client.
Maybe there are easier ways to achieve this, but if anyone interested, here is the server and client code:

server:

```javascript
ipc.config.id = 'localServer';

ipc.serve(() => {
    console.log('Server started!');
    ipc.server.on('message', (data, socket) => {
        //...
    });
    ipc.server.on('clientIntroduction', (data, socket) => {
        console.log('New client introduced as ' + data);
        socket.id = data; //save the client's socket id
    });
    ipc.server.on('socket.disconnected', (socket, destroyedSocketID) => {
        console.log('Client ' + destroyedSocketID + ' has disconnected!'); //now this works
    });
});

ipc.server.start();
```

client:

```javascript
ipc.config.id = 'localTest';

ipc.connectTo('localServer', () => {
    ipc.of.localServer.on('connect', () => {
        console.log('## connected to localServer ##');
        ipc.of.localServer.emit('clientIntroduction', ipc.config.id); //send socket id to the server
    });
    ipc.of.localServer.on('disconnect', () => {
        console.log('disconnected from localServer');
    });
});
```

**Comment by RIAEvangelist** [comment]
What you are looking for is a way to normalize the socket id across server and client. This is good for some applications and undesirable for others. I think the solution you have come up with is correct for your implementation. The intent of the ids is to allow them to be managed uniquely by the server irrelevant of the client so that the server can manage them in varied situations.

**Comment by frzsombor** [comment]
So this feature (the server knowing the original id of the client) is intentionally not implemented? I see that the requirement of this feature might be different in different implementations, but if that if this is the case, the 'socket.disconnected' event will never pass 'destroyedSocketID' to the callback and will always log 'false' in the [example code](https://github.com/RIAEvangelist/node-ipc/tree/10.1.0#server-for-unix-sockets-windows-sockets--tcp-sockets) by default.

**Comment by RIAEvangelist** [comment]
Which version are you running?

**Comment by frzsombor** [comment]
Running the latest v10.1.0

**Comment by RIAEvangelist** [comment]
I believe the intent is not for the ID to be normalized from client to server, but instead for the server to be able to assign ids to sockets so you can keep track of them.

Doing what you are doing is how you can normalize the ids from client to server, though, I would suggest allowing the server to set the ids because otherwise you could run into strange edge cases.
