### ISSUE TITLE
Who can fork it ?

### ISSUE THREAD

**Issue by bigshans** [RIAEvangelist/node-ipc#259]
It doesn't seem like the author thinks he's doing anything wrong. I don't think too much swearing is going to solve the actual problem, and a lot of projects still depend on it. So who wants to fork a copy for community maintenance?

**Comment by lukas-mertens** [comment]
I did fork it: https://github.com/lukas-mertens/node-ipc

You should not trust me either though, but it could help you as a starting point for your own fork. You can add it to your package.json like this:

```    
"node-ipc": "git+ssh://git@github.com:lukas-mertens/node-ipc.git",
```

Make sure to replace my username with yours after forking mine

**Comment by RIAEvangelist** [comment]
all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented. just lock the dep version.

**Comment by lukas-mertens** [comment]
@RIAEvangelist Actually, as much as I like the intention of what you did, this highlights that we can't be sure that future versions of node-ipc are free of malicious code. Therefore it is too dangerous to rely on a pinned version number, as this could lead to someone else, who doesn't know about the issues with its maintainer, bumping up the version number and injecting malicious code into the project. Of course this could happen in every other dependency as well, but as you have already proved to not be a source for trusted code, it is way too dangerous to rely on your personal opinion in the future. I can't be sure, that your personal opinion is against me next time. Nevertheless: Thank you for your development efforts so far. I hope you will be able to contribute to projects by trusted people in the future, so that we don't loose a valuable developer in the community. I hope that one day you will understand that what you did was unprofessional.

**Comment by RIAEvangelist** [comment]
fair enough.
