### ISSUE TITLE
GPL-v3 affecting this module

### ISSUE THREAD

**Issue by schamberg97** [RIAEvangelist/node-ipc#260]
Dear @RIAEvangelist ,

I’ve just seen this [issue](https://github.com/RIAEvangelist/node-ipc/issues/233). While I do not agree with you, I understand that I am in no power to change your mind.

However, your peacenotwar module is licensed under GPL 3. My concern is that its license also affects node-ipc, which is stated as MIT license. Considering that you are an author of both packages, I think it would make sense to do one of the following things: 

1) drop the peacenotwar package (I understand, not bloody likely)
2) change the license of peacenotwar package
3) make a license waiver for users of node-ipc, so that they don’t violate GPL license, when using node-ipc w/ peacenotwar in commercial projects

I understand that node-ipc probably wouldn’t count as derivative work, but many companies use automated systems to track licenses of the dependencies they use, which may prove to be a problem. As such, I really urge you to do measure number two or at least measure number 3, so things are a bit clearer for the whole community.

**Comment by MBRjun** [comment]
*I understand, not bloody likely*  
funny

**Comment by RIAEvangelist** [comment]
@schamberg97 can you provide a link or example of the license waiver. You make good points.

**Comment by majorendian** [comment]
the trashfire continues to burn the rest of the javascript ecosystem

**Comment by jukrb0x** [comment]
> License or no license, he should have released a new major version, if he wanted to include the peacenotwar package into node-ipc. So the existing code versioned as ^9.x.x or ^11.x.x would have stayed on that major branch. What he did can be considered a breaking change (literally breaking software on certain computers with certain IPs).
> 
> He should have released it as 12.0.0 or something and not patch versions, i.e. 9.2.2 etc. Anyway...

you never understand the trust in the open-source community, and the chain of trust is already broken in this project.

it is not just simple as a patch version or what lockfile can overpower.

Imagine the food/fruit/drink you have every day, today it's just an apple, tomorrow the farmers put some stickers on it for ad, and one day it is used as a politician troll by some people like the owner of the project. Apple can only be an apple to people, because we **trust** the apple is harmless to our body, we never know if the apple is poisoned unless someone has the first bite, and someone makes the apple malicious so gives it to the enemy/politician to eliminate them.

the same thing can happen to your family, your children, because we live in a world with people we trust, if you have no one to trust, even you are some special ops in the field, you still have supervisor and intel you must trust, you lived with a purpose, and that trust or I say belief (not religious) became the source power to complete the daily work in your life.

you entrust your children, or your family entrusts you to kindergarten/school while you were young, because you(or your family) believe the staff in school will never do harm to your children (or you), that is the most basic idea of trust.

**Comment by hms5232** [comment]
You can change license, release a new major version and add a description the README about this change.

IMO you may use LGPL on peacenotwar. LGPL keep package open but doesn't effect those project which use it.

**Comment by lorand-horvath** [comment]
> > License or no license, he should have released a new major version, if he wanted to include the peacenotwar package into node-ipc. So the existing code versioned as ^9.x.x or ^11.x.x would have stayed on that major branch. What he did can be considered a breaking change (literally breaking software on certain computers with certain IPs).
> > He should have released it as 12.0.0 or something and not patch versions, i.e. 9.2.2 etc. Anyway...
> 
> you never understand the trust in the open-source community, and the chain of trust is already broken in this project.
> 
I never understand the trust in OSS? Dude, take it down a notch, will ya?

**Comment by schamberg97** [comment]
> @schamberg97 can you provide a link or example of the license waiver. You make good points.

I can write you a waiver later, will send a PR, hopefully tonight

**Comment by waleed177** [comment]
MIT License is compatible... (not legal advice)

**Comment by waleed177** [comment]
My opinion is not just not use this repository and move the code to a different repository managed by a different person if this https://github.com/RIAEvangelist/node-ipc/blob/847047cf7f81ab08352038b2204f0e7633449580/dao/ssl-geospec.js was truely in this repository and was put by the owner of this repository.

**Comment by Uzlopak** [comment]
Yeah maybe compatible. But companies don't use GPL as you have to ship your software with a copy (=physical letter!) Of the GPL and potentially have to prove to not have your work being derivative work from the GPL licensed work. Fighting over intellectual property if you could avoid it by simply choosing a different software with MIT License is easier for a company.

So even if you add that waiver, a company won't invest time to check if your package waiver. They see GPL and then your software is already KO.
