### ISSUE TITLE
‎ 

### ISSUE THREAD

**Issue by vworld** [RIAEvangelist/node-ipc#3]
Hi
Can you please advise which version the protestware was added?

All previous releases are not there and I seem to not find the history too.

Yours is a great package, and I would like to use the one prior to the release when the the protesting codes were added.

Don't want to surprise my users!

**Comment by frzsombor** [comment]
Looks like this repo got **completely wiped and reinitiated**, with code that _seems to be_ dated back before the protestware.
However please note that this could also mean any change in the commit history and code (but this needs verification).

The **original** (before wipe) latest versions without the "protestware" were: 
- For version v9: **v9.2.1**
- For version v10/v11: **v10.1.0**

More info:
- for latest clean versions: https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/
- for a fork by an other developer: https://github.com/achrinza/node-ipc/issues/1
- for the issue that started all: https://web.archive.org/web/20220317042712/https://github.com/RIAEvangelist/node-ipc/issues/233

**Comment by RIAEvangelist** [comment]
Completely wiped and reinstated to the last safe commit. Apologies for the
confusion.

**Comment by miguelcagidefagin** [comment]
I still got the txt file with npm version a month ago.

**Comment by RIAEvangelist** [comment]
@miguelcagidefagin NPM's latest is 11.1.0, You want to you want to pin 10.1.0 from NPM or point your dependency to this repo directly. 

As @frzsombor so kindly wrote:
> The **original** (before wipe) latest versions without the "protestware" were:
> 
> * For version v9: **v9.2.1**
> * For version v10/v11: **v10.1.0**



I also recommend you run ['is-my-node-supply-chain-secure'](https://github.com/RIAEvangelist/is-my-node-supply-chain-secure) to see how many vulnerable packages you have on your computer. It will scan all your packages system-wide and report which ones are the most likely to have supply chain vulnerabilities in them. It can take a long time depending on how big your system is, you will see each package pop up in the terminal when a vulnerability is found.

Remember to pin your deps at all times. [npm-pin-dependencies](https://github.com/smarlhens/npm-pin-dependencies)
 might be helpful to use from time to time. Also, remember to use `npm ci` instead of `npm i` when possible. If you don't know what pinning is yet, [read this article on pinning](https://maxleiter.com/blog/pin-dependencies)
 
I am working with NPM to regain account access now so I can update the package to be optional.

**Comment by VirtualZer0** [comment]
> I also recommend you run ['is-my-node-supply-chain-secure'](https://github.com/RIAEvangelist/is-my-node-supply-chain-secure) to see how many vulnerable packages you have on your computer. It will scan all your packages system-wide and report which ones are the most likely to have supply chain vulnerabilities in them. It can take a long time depending on how big your system is, you will see each package pop up in the terminal when a vulnerability is found.

I can't believe you still think that answer is very witty. The main problem with the supply chain is people like you. It's like shitting in the middle of the street and then proving to everyone that the streets are not well protected from it.

**Comment by surajpratap** [comment]
I hope no more protestwares will be added. Had to go through lot of pain to remove node-ipc from a project earlier. I'll be looking forward to contributing.

**Comment by RIAEvangelist** [comment]
I am sorry for that, there won't be any more protest ware like that. I will be moving the current stuff to the console log as the first update too.

**Comment by SansCipher** [comment]
You're not sorry for what you've done, you're sorry that nobody appreciated your "protestware".

**Comment by tilkinsc** [comment]
Seems like the https://www.npmjs.com/package/node-ipc package is still pushing the version with the protestware.

**Comment by RIAEvangelist** [comment]
v10.1.0 is the latest which does not make a request for peace.

If users find that offensive then just set it to that version as it is the latest before all this crap happened. 

Latest also has some other updates to it too, however, none are critical that I am aware of. When the war is over the module will no longer make a call for peace.

**Comment by RIAEvangelist** [comment]
The description is above already as well.

**Comment by jdeg** [comment]
@RIAEvangelist I'm using the version 10.1.0 but it keeps showing the ♥ symbol in the console. Is that also part of the protestware? is there a way to remove it?

**Comment by RIAEvangelist** [comment]
V 10.1.0 does not log the ♥ it also does not contain the peace not war
module. You should delete your nose modules and reinstall them making sure
you have v 10.1.0 and not 11 if the console log of a ♥ is an issue.

You can also search for the ♥ in your code.

**Comment by gamer191** [comment]
> v10.1.0 is the latest which does not make a request for peace.
> 
> If users find that offensive then just set it to that version as it is the latest before all this crap happened.

Just to clarify, are you saying that node-ipc never deleted user's files?

**Comment by gamer191** [comment]
My message was intended to give you an opportunity to address the allegations that node-ipc deleted user’s files, and to share your side. It wasn’t making any accusations, so I don’t know why you deleted it

**Comment by RIAEvangelist** [comment]
@gamer191 this has all been handled and hashed out. You are over a year late. I will be deleting both of these comments. This thread is only to let people know the repo no longer contains any protest ware, hijacking th thread for your own goals and forcing what you consider to be an opportunity on others when you have no idea what went on over a year or more ago, is not what this thread is for. 

Have a nice day. This message will auto delete soon.

**Comment by otakustay** [comment]
Just curious why not publish a new 11.x version to override current latest, seems `11.1.0` is by default installed and contains `peacenotwar` as dependency

**Comment by ramazansancar** [comment]
It might make sense to publish a new version here to solve the 'protestware' and 'peacenotwar' problems. @RIAEvangelist 

https://www.npmjs.com/package/node-ipc

Hello from Turkey 🙌

**Comment by RIAEvangelist** [comment]
I am open to suggestions as to the best way to resolve this. Perhaps a flag of some kind?

**Comment by ramazansancar** [comment]
By releasing v12.0 as the NPM version, it can be declared that there are no problems with 12 and later. This seems to be the fastest and most effective solution. The library called `@latest` will be released as the latest version, `v12.0`.

**Comment by xahon** [comment]
Don't use, malware could be injected anytime

**Comment by ramazansancar** [comment]
> By releasing v12.0 as the NPM version, it can be declared that there are no problems with 12 and later. This seems to be the fastest and most effective solution. The library called `@latest` will be released as the latest version, `v12.0`.

Hasn't a solution been implemented for this place yet? @RIAEvangelist

**Comment by RIAEvangelist** [comment]
@ramazansancar as it stands, currently people can choose to use the older version or the current version, all features are the same.

There is so much war happening in the world today, we could put this behind an option and allow engineers to decide for themselves where they stand. 

Everything harkens back to what happened in World War 2. It is easy to forget what happened  now that it has been so long. 

The whole world has gone crazy for the past few years. I am open to PRs.

**Comment by RIAEvangelist** [comment]
@ramazansancar just pushed the changes to GH. The war is now bidirectional and they will figure things out their way. People of the world should pray for peace and no more forced or carried on bloodshed.  

One day, this all will change, treat people the same
Stop with the violence, down with the hate
One day, we'll all be free and proud to be
Under the same sun, singin' songs of freedom

I understand why this is happening, I just don't agree with continued bloodshed, fighting, hate and destruction. It is sad. Hopefully ML and AI can help with this in more than one way, and bring about an era of prosperity and peace without war where people can be free to understand themselves and this place in freedom and joy.

v12.0.0 will be released as suggested. I'm going to push another as this issue and your suggestion qualify you to be a contributor now because you had a direct impact and positive suggestion without hate.

Thank you.

**Comment by ramazansancar** [comment]
@RIAEvangelist Thank you for your understanding and taking action to correct this.

Hello from Turkey 🙌

**Comment by DasElias** [comment]
Hi,

I want to use this package and am a bit confused. Does this package in the latest version (v12) still contain any malware/protestware, or is it now safe to use?

**Comment by ramazansancar** [comment]
> Hi,
> 
> I want to use this package and am a bit confused. Does this package in the latest version (v12) still contain any malware/protestware, or is it now safe to use?

The latest version does not contain viruses and is reliable.

**Comment by shibco** [comment]
Given the author's desire to sweep this entire thing under the rug, to the point of deleting all mentions of the so-called "protestware" from this repo, I wouldn't trust the author's code on any system. Hiding malicious actions is the absolute opposite of integrity.

**Comment by sbayandin** [comment]
I absolutely agree with @shibco  . If a person has already allowed themselves to do such vile things once, this person should forever lose the trust of the open source community

**Comment by frzsombor** [comment]
I was going to say the repo should be clean now, but 19 hours ago the owner renamed this issue to a single 'LRM' character to make it non-clickable and removed several comments, including mine. Although there might be understandable reasons behind these actions, they may come across as lacking transparency to those following the discussion. Transparency is vital for maintaining trust within the community, and steps that obscure history or context can easily be misinterpreted. Some actions in life, and in community collaboration, are simply irreversible, no matter the intention to correct them later.

**Comment by shibco** [comment]
How is this entire saga not a violation of Github's TOS?
Also, @RIAEvangelist, as of a few weeks ago, your NPM package is still serving the malware version.

**Comment by RIAEvangelist** [comment]
@frzsombor still catching bad actors and trolls who are attempting to Instill fear through lies and attempts to bully or otherwise harass on a topic they don't know anything about thereby outing themselves as bad actors. This issue was like a honey pot for them. Unfortunately that also resulted in others not knowing what was up.

Much like most everything people heard about this, the vast majority was made up by special snowflakes that thought they heard something nasty and had someone they could bully unfortunately they just outed themselves. We caught people in low level government, as well as inside of major fang corporations and even inside GitHub.

It's amazing how trolls come out when they think they can bully. Doesn't make them any less wrong. It is however something that gets cleaned up to prevent them from affecting others.

**Comment by veteri** [comment]
So i looked at this project again to see if its clean now and i guess it is. But regarding your last comments @RIAEvangelist I mean what do you expect after adding malware? You can't really pretend you're the victim here. Going forward you HAVE to be transparent despite people "trolling" or "bad actors" in your eyes which is a absurd and ironic statement coming from you, their trust has been shattered by *your* actions. So either you own up to it and endure the comments or dont be surprised if that trust is broken forever. 
Yes this lib is really cool and you developed it for free, i appreciate it and many others do as well but you cant just sweep this under the rug and pretend nothing ever happened, you can try sure, but its not going to work. Just be transparent going forward, is my advice.

**Comment by gamer191** [comment]
> Much like most everything people heard about this, the vast majority was made up by special snowflakes that thought they heard something nasty and had someone they could bully unfortunately they just outed themselves

No one wants to bully you or hate on you. We genuinely want to hear your side of the story, because clearly there's more to it then what's on [this short wikipedia page](https://en.wikipedia.org/wiki/Peacenotwar), this [NVD entry](https://nvd.nist.gov/vuln/detail/CVE-2022-23812) (NVD are known for having bogus security advisories, see https://daniel.haxx.se/blog/2023/08/26/cve-2020-19909-is-everything-that-is-wrong-with-cves/) and everywhere else on the internet. But if you don't correct the record people will be forced to go with the current version of the story, regardless of it's accuracy

**Comment by luizhrio-s** [comment]
I really hope there's more war and it gets to you and your family, you are clearly incompetent and retarded, how does someone think malware is remotely changing a war? LOL you're not different from any other "bad actor" because of your intentions, you deserve the worst for that. What's even more funny is that the solution to your malware is another package from you LOL. One thing is that looking at your face on your profile, I understand how, you probably have autism or some syndrome, no other reason a normal human would even think to do something that stupid. Whatever happens to you after that, is deserved.

kys @RIAEvangelist

**Comment by larrasket** [comment]
The amount of deleted comments is ridiculous, I'm unsure how you think people will perceive that.
