### ISSUE TITLE
russians(with active passports) should be disconnected from the whole developer's community

### ISSUE THREAD

**Issue by Borowing** [RIAEvangelist/node-ipc#307]

**Comment by ketsushiri** [comment]
You're right, Adolf Hitler.

**Comment by madfrag** [comment]
Adolf, please re-login

**Comment by Borowing** [comment]
I'm Adolf Hitler? look at what I said - the country that attacked my country should be canceled on all fronts, and I mean any russian  citizens - they choose that piece of shit to be a president

**Comment by fdog** [comment]
Russians don't choose him

**Comment by Borowing** [comment]
hmmm, so who then?

**Comment by vshymanskyy** [comment]
[![Russian Warship Go Fuck Yourself](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://vshymanskyy.github.io/StandWithUkraine)

**Comment by Borowing** [comment]
@READYTOMASSACRE say it to vladimir putin

**Comment by icmx** [comment]
dude, seriously?

**Comment by TheMisterSenpai** [comment]
mmm, nice

**Comment by READYTOMASSACRE** [comment]
No one forbids you to hate anybody, but this platform has rules, so please follow it

**Comment by Trendyne** [comment]
\>Putler is a fascist that doesn't allow fair elections!
\>Also every Russian is responsible for anything he does!

Still on the low-level for liberal double-think

**Comment by thecoomer** [comment]
I think a village somewhere is missing their idiot.

**Comment by bopm** [comment]
Ever heard of the fact that if you are born into Russian citizenship you cannot leave it before Putin himself signs a decree about abolishing your citizenship? Aside from getting allowance from every government agency and proving that you have another citizenship to acquire?

**Comment by dtantsur** [comment]
> If Ukraine has done it, why russians cannot do it?

Because the situation in the countries are completely different? Because in Ukraine nobody has been destroying democracy for 20 years? Because Ukraine didn't have more than 300000 (300 thousands, more than your whole army, I suspect) Rosgvardia fighters specifically dedicated to suppressing internal resistance with violence? Because more people were arrested for protesting against the war than died in Ukraine?

I understand your grief, but it won't get you anything...

**Comment by ketsushiri** [comment]
> any person with russian citizenship can protest -> if these persons will be a lot -> the Russian regime will fall

And not only with the citizenship, you know. We have something around here, called "human rights". The fun part is -- it's only on paper.

6 march, anti war protests:
More than 2000 protestors around Russia, mostly in Moscow and St. Petersburg.
More than 1700 arrested.

It was a peaceful protest btw. Me also was arrested, now I have to pay 15000 rubles (around 160 dollars, i suppose) penalty, which is around 1/3 of average salary over here. And i got not only the penalty as the result, but problems with my school, job, other goverment structures and so on.

Now let me tell you what happens when you got arrested on those protests. First of all, documents and telephones will be will be withdrawn, despite it is against the Constitution, our fascist regime servants doesn't care much, and if you not ready to assert your rights against bandits in masks for about 12 hours, then you probably will have to accept their rules. Therefore, there will be no way to contact someone for around future 12 hours. In worst case -- around 15 days. Many such cases. Next there will be most interesting part -- the protocols drafting. It is not a problem, that they can write there anything they want, you anyway 'll have the choice to accept or not. And if it's not, then you'll have to proof it in a court, not a big deal. But you have to wait for around 6 hours and all this time there will be absolute fuckers from FSB, who will try to scare the fuck out you, say, that the is a more, than just administrative fault, but even criminal. Gestapo at minimals. So after 4 or 5 talks, if you aren't really strong in spirit and not complete sure about what happened and do not fully know your constitutional rights, then you probably will accept their conditions. And then penalty can be much more. 

For the kinda third world country 150-250 dollars is a big money, you know. And also future problems because of arrest. 

Just like, this how it works over here. Not many people are ready to, for example, lose their carier, or get excluded from uni, etc. The probably strongly disagree with the situation, but it is not 1917 or 1991/93, when society was on it's limit and has nothing to lose.

**Comment by Borowing** [comment]
Yeah I know that to be a protester in russia isn't funny, as it wasn't on euromaidan, but without protesting, there no ways to stop it, so I think as fast ordinary life of every russian gonna down, then the fast russian regime will fail

**Comment by joshuaalayon** [comment]
> [![Russian Warship Go Fuck Yourself])]

about as real as the ghost of kiev

**Comment by Borowing** [comment]
> > I'm Adolf Hitler? look at what I said - the country that attacked my country should be canceled on all fronts, and I mean any russian citizens - they choose that piece of shit to be a president
> 
> Next time don't allow Azov Nazis to fly swastikas and other anti-semitis BS logos on official uniforms and maybe this doesnt happen, mmkay?

Azov is nazis? that's funny, there are not any proves of it, only some photos, that I can find also in russia

**Comment by joshuaalayon** [comment]
> > > I'm Adolf Hitler? look at what I said - the country that attacked my country should be canceled on all fronts, and I mean any russian citizens - they choose that piece of shit to be a president
> > 
> > 
> > Next time don't allow Azov Nazis to fly swastikas and other anti-semitis BS logos on official uniforms and maybe this doesnt happen, mmkay?
> 
> Azov is nazis? that's funny, there are not any proves of it, only some photos, that I can find also in russia

Next time, don't allow Nazis into your National Guard, and Russia won't have to denazify you.

It's that simple.

As a Jew myself, your Azov Nazis trying to do a 2nd Holocaust, that's absolutely unacceptable to me.

**Comment by Borowing** [comment]
> > > > I'm Adolf Hitler? look at what I said - the country that attacked my country should be canceled on all fronts, and I mean any russian citizens - they choose that piece of shit to be a president
> > > 
> > > 
> > > Next time don't allow Azov Nazis to fly swastikas and other anti-semitis BS logos on official uniforms and maybe this doesnt happen, mmkay?
> > 
> > 
> > Azov is nazis? that's funny, there are not any proves of it, only some photos, that I can find also in russia
> 
> Next time, don't allow Nazis into your National Guard, and Russia won't have to denazify you.
> 
> It's that simple.
> 
> As a Jew myself, your Azov Nazis trying to do a 2nd Holocaust, that's absolutely unacceptable to me.

any proves? They live quietly, we have a Jewish president, we have Jewish oligarchs, Jews come to us every year in Uman, and in general, many Jews live in Ukraine, and many Jews in Israel support Ukraine, so I wish you to quickly move away from russian propaganda

**Comment by Borowing** [comment]
@joshuaalayon lol, where you've found that I was saying it? Okay, maybe Zelenskyy's Judaism and Israel support are saying you nothing, but jews, with various confessions living in Ukraine in peace, and it's a fact.

**Comment by joshuaalayon** [comment]
> @joshuaalayon lol, where you've found that I was saying it? Okay, maybe Zelenskyy's Judaism and Israel support are saying you nothing, but jews, with various confessions living in Ukraine in peace, and it's a fact.

Jews like me also lived in Nazi Germany
A lot had no idea what was happening until they were rounded up, and also would have said they lived in Germany in peace
Your Nazi propaganda doesn't work on me, I am Jewish, when I see National Guard of a nation flying swastikas, I know exactly what that means.

https://wiki.holocaust-facts.com/index.php?title=Refuting_the_Lie_that_Zelenskyy%27s_Alleged_Judaism_Somehow_Excuses_His_Nazism

Next time do not allow Nazis in your military and Russia won't have to denazify you. It is that simple, really.

**Comment by joshuaalayon** [comment]
> > 
> 
> hm, do you have any proof of an action of azov that is a nazi action? as I said, I also can find a lot of these photos in russia

Next time don't let Nazis into your military

Flying swastikas freely

And no one will have an excuse to denazify your Nazi country
Simple as

https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing

**Comment by Chityanj** [comment]
*Guys agent Orange was health suppliment and lives of middle East did not matter as they were subhumans

**Comment by Borowing** [comment]
> > > 
> > 
> > 
> > hm, do you have any proof of an action of azov that is a nazi action? as I said, I also can find a lot of these photos in russia
> 
> Next time don't let Nazis into your military
> 
> Flying swastikas freely
> 
> And no one will have an excuse to denazify your Nazi country Simple as
> 
> https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing

Yeah yeah, photos of swastikas are enough for you, okay

**Comment by CamaroSS** [comment]
Go fork some repos pls.

**Comment by joshuaalayon** [comment]
> > > > 
> > > 
> > > 
> > > hm, do you have any proof of an action of azov that is a nazi action? as I said, I also can find a lot of these photos in russia
> > 
> > 
> > Next time don't let Nazis into your military
> > Flying swastikas freely
> > And no one will have an excuse to denazify your Nazi country Simple as
> > https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing
> 
> Yeah yeah, photos of swastikas are enough for you, okay

Photos of swastikas being flown by a Nations official Army? Oh yeah, as a Jew whose family members suffered in the Holocaust, you better believe that when a nations official armed forces take up swastikas, I know EXACTLY what that means.
https://wiki.holocaust-facts.com/index.php?title=Just_who_are_the_Azov_Battalion%3F_Meet_Ukraine%27s_strongest,_most_elite_and_well-decorated_National_Guard_unit,_who_proudly_fly_swastikas_on_their_uniforms_and_military_vehicles,_and_have_Zelenskyy%27s_full_approval_and_blessing
