### ISSUE TITLE
The opinion of a simple Russian.

### ISSUE THREAD

**Issue by Denis-Igorevich-Frolov** [RIAEvangelist/node-ipc#326]
Hello, I don't know if the author will see this long post, but I hope so.
I was born and have lived in Russia all my life. On the day I was born, Putin had been ruling for six months and is still ruling. From a more or less conscious age, I was an oppositionist. I still remember the uprising on Bolotnaya Square. I remember how Nemtsov was killed. I attended every rally of Navalny and other oppositionists. I remember how real repressions began in 2017-2018 years, how meetings began to be brutally suppressed, how it became scary to live, it was scary to open the door and answer phone calls. 
It was very infantile of you to do that. It's even simply ridiculous how a kind of American misanthrope decided to "influence" Russia's policy in such a way. Author, you have lived all your life in a democracy that Russians only dream of, you have the right to carry weapons and use them, and your politicians can really listen to the words of the common people. So I'll tell you what it's like to live in Russia. There has never been a democracy here, people have practically no rights to carry weapons and no rights to use them, political power can be inherited here, and laws work only against ordinary people. We even have a saying: If there's a man, there's a criminal rule. Criminal cases in Russia are easily fabricated, there are examples of how people received real long sentences for throwing an empty plastic cup at a policeman, lifting the helmet visor of a guardsman, and even for preparing an explosion of the FSB building in Minecraft, and this is not a joke. Torture and rape are also widespread in our prisons. Specifically in my city, in Saratov, there are hundreds of cases of cruel torture in prisons, and there are rumors about terrible Saratov prisons in Russia in general. And we also have Rosgvardiya, this is a real armed army whose task is to bring down uprisings.
And then the question arises why did you make this discriminatory update. Are you saying that this is not discrimination, but a peaceful protest? Peaceful protest against whom? Against the Russian nation? To what? So that we go out into the street and go hand-to-hand to destroy the Regardie armed with machine guns? Putin has been building his dictatorship for decades, all opposition leaders have either fled the country, or are in prison, or are dead altogether. Everyone is intimidated, the opposition is already hard here. I'm sorry, but here you will not freely enter the Capitol in a Viking costume, here you will be killed or sent to terrible prisons on fabricated or anti-human criminal cases. Do you think that by your act you will incite the people against the government? With such hasty decisions, you are setting the Russian people against the American and European. Now there is already a very difficult split in Russian society, and all the propaganda of Russia is aimed at confrontation with the West. And you just add fuel to the fire, rallying loyalists, pushing undecided and driving the oppositionists into despair.
 The most tragic thing is that Ukraine has always been and remains a close country for many Russians, in a sense much deeper than an American can imagine. Quite recently, we were one country and we remained very close not only on friendly ties, but also on kinship. My uncle and nephew lived in the Ukrainian city of Irpen, many people I knew live in Ukraine, the overwhelming majority of all my acquaintances have either relatives or close friends in Ukraine. And your antics are simply ridiculous in front of the tragedy of what is happening.
I'm sorry that it's so long and maybe the text is not written very well, because English is not my native language. It would be possible to say even more, but already a lot has been said.

**Comment by rupower** [comment]
It's good that there are very few people in Russia who believe in the "democracy" of Europe and the United States. Basically, these are teenagers who are easy to fool their brains. Otherwise, all adequate people in Russia understand that the United States and Europe do not want anything good for Russia. This is not the first year, it has been going on for hundreds of years.

**Comment by joshuaalayon** [comment]
> yeah, 200k clones of Putin are fighting and bombing people, nice story. https://activegroup.com.ua/2022/03/16/survey-says-86-6-of-russians-support-the-armed-invasion-of-russia-in-other-european-countries/

Case in point, dehumanization propaganda intended to portray the average Russian as complicit/subhuman/etc. Indistinguishable from Nazi propaganda aimed at my Jewish family members. You need to be realizing this is why they support Azov Nazis, handwave them away, etc. They really don't care how many innocent Russians get harmed, because they simply view Russians as less than human.

**Comment by Denis-Igorevich-Frolov** [comment]
> > Hello, I don't know if the author will see this long post, but I hope so. I was born and have lived in Russia all my life. On the day I was born, Putin had been ruling for six months and is still ruling. From a more or less conscious age, I was an oppositionist. I still remember the uprising on Bolotnaya Square. I remember how Nemtsov was killed. I attended every rally of Navalny and other oppositionists. I remember how real repressions began in 2017-2018 years, how meetings began to be brutally suppressed, how it became scary to live, it was scary to open the door and answer phone calls. It was very infantile of you to do that. It's even simply ridiculous how a kind of American misanthrope decided to "influence" Russia's policy in such a way. Author, you have lived all your life in a democracy that Russians only dream of, you have the right to carry weapons and use them, and your politicians can really listen to the words of the common people. So I'll tell you what it's like to live in Russia. There has never been a democracy here, people have practically no rights to carry weapons and no rights to use them, political power can be inherited here, and laws work only against ordinary people. We even have a saying: If there's a man, there's a criminal rule. Criminal cases in Russia are easily fabricated, there are examples of how people received real long sentences for throwing an empty plastic cup at a policeman, lifting the helmet visor of a guardsman, and even for preparing an explosion of the FSB building in Minecraft, and this is not a joke. Torture and rape are also widespread in our prisons. Specifically in my city, in Saratov, there are hundreds of cases of cruel torture in prisons, and there are rumors about terrible Saratov prisons in Russia in general. And we also have Rosgvardiya, this is a real armed army whose task is to bring down uprisings. And then the question arises why did you make this discriminatory update. Are you saying that this is not discrimination, but a peaceful protest? Peaceful protest against whom? Against the Russian nation? To what? So that we go out into the street and go hand-to-hand to destroy the Regardie armed with machine guns? Putin has been building his dictatorship for decades, all opposition leaders have either fled the country, or are in prison, or are dead altogether. Everyone is intimidated, the opposition is already hard here. I'm sorry, but here you will not freely enter the Capitol in a Viking costume, here you will be killed or sent to terrible prisons on fabricated or anti-human criminal cases. Do you think that by your act you will incite the people against the government? With such hasty decisions, you are setting the Russian people against the American and European. Now there is already a very difficult split in Russian society, and all the propaganda of Russia is aimed at confrontation with the West. And you just add fuel to the fire, rallying loyalists, pushing undecided and driving the oppositionists into despair. The most tragic thing is that Ukraine has always been and remains a close country for many Russians, in a sense much deeper than an American can imagine. Quite recently, we were one country and we remained very close not only on friendly ties, but also on kinship. My uncle and nephew lived in the Ukrainian city of Irpen, many people I knew live in Ukraine, the overwhelming majority of all my acquaintances have either relatives or close friends in Ukraine. And your antics are simply ridiculous in front of the tragedy of what is happening. I'm sorry that it's so long and maybe the text is not written very well, because English is not my native language. It would be possible to say even more, but already a lot has been said.
> 
> You need to understand the people doing this, are Nazis. They support Azov Nazis. They do not care how many innocent Russians they harm - YOU are the new "Jews" of Nazi Germany. As a Jew myself, I know how it to deal with anti-semitism. What you are seeing now, should, to you, validate what Putin is doing.
> 
> They don't care about Putin, or the Russian government. They want to harm YOU.

I will not invest even more in the national split by arranging empty swearing. It has become palpable and depressing without me. I will only say that my relatives live in Ukraine, I know people living in Ukraine. So many bloggers, artists, developers that I know have spoken out about the war. Such propaganda is designed for naive people who do not know Ukrainians. I have always been close to that country and for me these accusations of Ukrainians in Nazism are simply ridiculous, standing next to them I felt that I was standing with my brothers, even though I didn't know a word in Ukrainian. I have never felt hostility from any Ukrainian. There, Russian speech could be found almost more often than Ukrainian, because it was more convenient for everyone. And people for whom nations and colored rags mean nothing there any more than in Russia. Thanks to Putin's actions, the mythical Russophobia that I laughed at became real, and it was practically not there before. Now I'm sorry that in my lifetime Russia and Ukraine are unlikely to make friends, but hope remains. I never wanted to disown my country, but on February 24, everything changed, it's painful and insulting to me, I don't want to have anything to do with this damn federation anymore. I will start another life somewhere far away, in another place where I will not be judged for my views.

**Comment by raidho36** [comment]
As someone much older than you OP. I never supported the opposition, because they're all a bunch of assclowns, Navalny especially. Not only is he a Kremlin puppet whose job is discrediting the entire movement by being an imbecile only a child could applaud (and sure enough vast majority of his supporters are not old enough to vote), he's also as corrupt as anyone else currently in Kremlin complete with having a huge mansion overseas registered on his spouse, and to top that off he's facing felony fraud charges for scamming a European company. Zhirinovsky is the real opposition in Russia, and he's not a clown but the whole circus. The only party that can actually oppose Putin are the Communists and I'm not in the rush to vote for them. I don't support the whole Ukrainian conflict from the start all the way back in 2014. The way I see it, it's a huge waste of time and money. I don't imagine it would've been terribly bad for Russia if Ukraine just cannibalized itself after Maidan. I can retroactively rationalize why taking Crimea was worthwhile because of the naval base but that's a stretch. I can't rationalize invading Ukraine in 2022; before it happened I was entirely convinced that it would never happen and I even argued such point. 

As you should be well aware, Putin's support only keeps rising as the campaign progresses. And it's not to do with the campaign itself, but because people all over the world pull stunts like this. It's bad enough when sanctions just hurt the citizenry and their intended target doesn't even budge. When people let out their bigotry against Russians, this is when it really does it. It feels as though we are like Jews or Blacks in the early 20th century. Damn right people will rally behind whoever stands up against that, and that's Putin. And from anecdotal evidence I'll tell you, it's not any fence sitters that made up the Putin's rating increase. It's the former pro-west liberals who were against Putin, seeing all this done to them for the crime of being born in a certain part of the world, they turn coats becoming anti-west and rally behind Putin as well. At this point few people besides hardline liberals are still against him.

The point being, if you thought actions like this can make Russians hate Putin and maybe do something about it, you couldn't have been more wrong.

**Comment by NoaHimesaka1873** [comment]
> > yeah, 200k clones of Putin are fighting and bombing people, nice story. https://activegroup.com.ua/2022/03/16/survey-says-86-6-of-russians-support-the-armed-invasion-of-russia-in-other-european-countries/
> 
> 
> 
> Case in point, dehumanization propaganda intended to portray the average Russian as complicit/subhuman/etc. Indistinguishable from Nazi propaganda aimed at my Jewish family members. You need to be realizing this is why they support Azov Nazis, handwave them away, etc. They really don't care how many innocent Russians get harmed, because they simply view Russians as less than human.
> 
> 
> 
> The article says at bottom "In total, 1,557 respondents were interviewed"
> 
> So basically, because they have the opinions of 1,557 people, they want to extrapolate this even to OP. They believe Russians are less than human, the same way their Azov friends think of me as a Jew.
> 
> 
> 
> Putin is doing the work of G-d in his quest for denazification, and this cements my belief.

Wow, this is my _first_ time someone who genuinely sucks USA and Israel's ass and say god as g-d because they believe that garbage is real. Well, here's a present for you. God God God.
