### ISSUE TITLE
Need Information on large message crash

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/node-ipc#36]
@j33f 

Can you provide the steps needed to reproduce the crashes you prevented with pull request #34

I'd like to know what was causing these at a deeper level.

**Comment by j33f** [comment]
Into the Kuzzle project (soon to be published) we where using node-IPC as an internal message broker. Kuzzle aims to be a BAAS with ElasticSearch as a persistent data storage. In order to populate the storage, we were pushing some huge bulk sets (100k+ records)  and node-IPC was fine with the first ones, but fastly starts to bufferize then crashed because of the JSON.parse not recieving a well formed stringified JSON or because the ipcBuffer was too small (when buffizing the next unfinished message).

I tryed to use an array of buffers (strings), adding to the last unfinished buffer entry, the last recieved message piece. It made the job but the perfs were very very bad... at the end, the patch I proposed was the less impacting solution to get things work.

Now we have replaced node-IPS by a websocket system that offers no crashed, blazing fast operations and support 1M+ bulk messages. The bulk process that was taking 2hrs and crashing before the patch, then 3hrs with the patch via node-IP is now taking 12min for thousands bulks of 100k+ rows.

Hope this helps you to understand. Feel free to ask if you need more informations.

**Comment by RIAEvangelist** [comment]
Thanks for all your feedback, it is very helpful! Was this over a network socket?

If it was over the network, I bet if offering gzipping or compressing such huge messages, that might help a lot too. Perhaps that is something we should consider.

I also wonder if the new rawBuffer (binary) support we added in could be of use in speeding things up even more.

**Comment by j33f** [comment]
nope it was the same docker container...

**Comment by RIAEvangelist** [comment]
OK, so all over unix socket then. That should be the fastest way, always.

I am very interested to try and fix this even though you are not using node-ipc anymore. Unix socket should be much faster than websocket especially on same container.

I created a new branch called large-messages to work on this. If you are able, it would help a lot if you could review the effects of the changes to see any improvements.

**Comment by j33f** [comment]
at the end, the websocket will help us to separate the components into several docker containers and servers, that is the final goal. This will help us for scalability and ease to plug some middlewares of listeners even if, yep, using unix sockets are the faster way. But, hey, if node-IP become as fast and as easy, we may come back using it you know ;)

**Comment by RIAEvangelist** [comment]
I believe a TCP socket should still be faster than a web socket.

A web socket is like a TCP socket, but websockets have more built on top so they should be slower.

Is there any way you could provide me some example messages so I can do some benchmarking?

**Comment by j33f** [comment]
yep but the "build on top" things makes a difference actually

For the messages, that is simple : the data bulk was a array of 100k+ objects with 5 strings (from 2 to 20 chars) and 5 decimal values passed from a server and a worker

**Comment by RIAEvangelist** [comment]
do you still build the array and objects the same way now?

**Comment by j33f** [comment]
yep, its a bulk for ElasticSearch

**Comment by RIAEvangelist** [comment]
Seems to be fixed with node > 4.0.0 and rawBuffer set to true.

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
