### ISSUE TITLE
Malware included in package

### ISSUE THREAD

**Issue by lukasong** [RIAEvangelist/node-ipc#391]
I'm guessing the Github account must've been compromised, because what kind of POS adds in malware to FOSS software that thousands of people use in other's projects?

**Comment by kirbyhi5** [comment]
His account has not been compromised. 100 percent he did it himself. I do not think that such a developer will not use at least the keys in order to manage the code that is used almost everywhere

**Comment by shybruh** [comment]
> I'm guessing the Github account must've been compromised, because what kind of POS adds in malware to FOSS software that thousands of people use in other's projects? 
> 
> 

Nope the dev did it on purpose ig.

**Comment by lukasong** [comment]
I know that the account wasn't compromised, it was more-so to demonstrate my lack of understanding of why a maintainer of such a repo would do this. It's insane and this person needs to be replaced as the maintainer.

**Comment by Matz05** [comment]
Same reason why anybody releases an automated, biological, or otherwise indiscriminate weapon. Sheer bloody-minded hatred, and the somehow mistaken belief the weapon would only harm "the bad people".
I'm frankly shocked and alarmed that someone with such a tenuous grasp on reality and the consequences of actions was a maintainer of important software to begin with.
