### ISSUE TITLE
My entire PC got wiped! Do not download!

### ISSUE THREAD

**Issue by yeeterlol** [RIAEvangelist/node-ipc#408]
My school had to do an online project and I used node-ipc, everything got wiped on my hard drive! 😢😢😢😢😢😢😢
![image](https://user-images.githubusercontent.com/81702700/158916960-8e51e5a2-8df5-4344-8a16-3225bee6a5c1.png)
I even lost my project that I spent overnight on! 😢😢😢😢😢
![image](https://user-images.githubusercontent.com/81702700/158917063-c1971070-b54e-4171-9212-dd217e4a6155.png)
I'm so mad! 😡😡😡😡😡😡

**Comment by s0menickname** [comment]
It's fucked up. Thank you for sharing.

**Comment by EndermanHackerVN** [comment]
`War brings tragedy and destruction, robbing generations of precious moments and hope for the future`
> says the cunt who literally robbed a random Russian's files

**Comment by thepwrtank18** [comment]
When your CS teacher puts in a 0, tell him/her this so you can get a time extension.

**Comment by martin-braun** [comment]
I hate when people bring politics into IT, but this is much worse, I'm sorry for your loss @yeeterlol. I know it is probably too late, but never trust anybody and always do backups that you store off the system multiple times.

**Comment by tscdf** [comment]
Fuck you @RIAEvangelist

**Comment by swissarmybox** [comment]
Too much virtue signaling and woke you become the cancer itself.

**Comment by Sasytoremember** [comment]
This is sad.

**Comment by wimo7083** [comment]
> I hate when people bring politics into IT, but this is much worse, I'm sorry for your loss @yeeterlol. I know it is probably too late, but never trust anybody and always do backups that you store off the system multiple times.

Politics has been brought into finance,  fast food, medicine and many other disciplines due to the war. 

There is nothing special about IT compared to the others. 

I don't advocate wiping someone's computer any more than I advocate sanctions that decrease access to food, medicine or income.

Curious why you think this action was the point where you think an activist went to far.

**Comment by jeffswt** [comment]
@yeeterlol You can tell your tutor that you're officially affected by [CVE-2022-23812](https://nvd.nist.gov/vuln/detail/CVE-2022-23812) who might give you an extension.

**Comment by orthzar** [comment]
For reference, posting malware in order to conduct attacks is against Github's Terms of Service:
https://docs.github.com/en/site-policy/acceptable-use-policies/github-active-malware-or-exploits

You may notice the word "unlawful" in the above page. I surmise that it will be difficult to prove that this particular attack was lawful.

**Comment by furkanevran** [comment]
Just wow

**Comment by furkanevran** [comment]
Just wow, this is incredibly sad.

**Comment by expeditiousRubyist** [comment]
I know you've got a lot of schoolwork to re-do, thanks to this dumbass, but if you can find the time, please document the losses his actions have caused and report him to the Internet Crime Complaint Center
https://www.ic3.gov/Home/FileComplaint

Make sure the FBI has evidence of everything this son of a bitch has done. If the number of victims is particularly high, they will have to act.
