### ISSUE TITLE
Does the US prosecute its citizens for carrying out acts of cyber terrorism?

### ISSUE THREAD

**Issue by heidenrei** [RIAEvangelist/node-ipc#486]
https://en.wikipedia.org/wiki/Cyberterrorism

**Comment by expeditiousRubyist** [comment]
Am not a lawyer, but there is a law Brandon (I will be referring to him by the name he has used in his profile) violated here, called the Computer Fraud and Abuse Act. The relevant text can be found here:
https://www.law.cornell.edu/uscode/text/18/1030#a_5

There are two components to this law that are relevant.
1. Did Brandon access a protected computer while exceeding authorized access? Yes. The definition of "protected computer" here is "anything engaged in interstate or international communication", which is basically anything with an Internet connection. And the exceeding authorized access part comes from the NPM terms of service that were violated. Since the software Brandon uploaded during his update included malware, it violated the ToS, and thus constitutes an unauthorized access to their servers. It is also worth noting that Github ToS was also violated. 
2. Did Brandon cause damage as a result of his unauthorized access? Yes. As we have seen in previous posts, Brandon's actions caused destruction of evidence of an NGO's Belarusian servers.

Needless to say, Brandon Nozaki Miller has violated 18 U.S. Code § 1030 (a)(5), which is punishable by a prison sentence of up to 10 years, or a fine, or both. If you believe you have evidence that could help lead to his conviction, which has not otherwise been aggregated by his victims (who have indicated that they intend to press criminal charges), you can submit a tip to the IC3 (the FBI's Internet Crime Complaint Center).
https://www.ic3.gov/Home/FileComplaint
