### ISSUE TITLE
[Discussion] Why are Americans this way?

### ISSUE THREAD

**Issue by jonathan-rosa** [RIAEvangelist/node-ipc#493]

**Comment by Coolsonickirby** [comment]
As an American, I sincerely apologize on behalf of the idiots in our country. 

It sucks living and being grouped with them 😔

**Comment by jerbear2008** [comment]
yep

**Comment by vxiiduu** [comment]
Americans are the way they are due to the copious amounts of burgers and coca cola they consume on a daily basis.
Obsesity rots the brain. The rest is self explanatory.

**Comment by BrandonHuu** [comment]
It's because of how they are indoctrinated. It's always a Us vs Them mentality for them.

**Comment by TDR-MGTOW** [comment]
make sure to donate soy to his wife's boyfriend.

**Comment by archering** [comment]
they are  brainwashed poor people

**Comment by PeaceNIRA** [comment]
hahaahahahahhahahahahahhahahaahhaha how dumb must you be to literally attempt to ruin people's lives over something they have 0 control over.

**Comment by swampservers** [comment]
They put a lot of estrogens in our food

**Comment by superggn** [comment]
Look on the bright side, maybe he's not an idiot, just got some money from politicians LOL

**Comment by TheShermanTanker** [comment]
Loud minority, I'm sure there are way more good Americans around

**Comment by CoderEx24** [comment]
because they think they are better than everyone else because they have the strongest millitary in the world.
they think that their word is law and that they are always right.

what are you going to do about it?, go to war?, have fun getting bombed out of existence.

**Comment by Uzlopak** [comment]
Let's don't prejudice against all US-Citizens. 
I assume Brandon is one of those guys who didn't serve in the military because there is no draft. Unlike other countries were you are drafted and know how dull and pointless wars are. Also why should he know how it is to live under a regime or dictatorship? Most of the world is oppressed. Freedom comes usually drop-by-drop and not with revolutions. Revolutions usually throws a country about 50 years back in the aspect of personal freedom.  Before this a revolution first eats his children. 

So arm-chair revolutionists like Brandon will do these childish things with good intentions. But the road to hell is paved with good intentions.
