### ISSUE TITLE
The ABSOLUTE STATE OF NODE

### ISSUE THREAD

**Issue by bernardgut** [RIAEvangelist/node-ipc#527]
And this my friend is why no one takes nodejs and generally front-end centered frameworks for production infrastructure seriously. 

Grown ups don't have time for this.

**Comment by dark-swordsman** [comment]
Correct, but then that's why a lot of the developers that end up writing JS don't have the standards or practice that other languages usually provide. The people that know other languages hate JS and don't attempt to learn it or see why it's useful.

So I would appreciate that people stop shitting on JS and instead try to help it. They could very easily propose changes to to the ECMA foundation, push for changes in npm/github regarding packages like this, etc.

**Comment by RIAEvangelist** [comment]
Its not so bad if we just try our best to follow best practices and lock package dependency versions.

I learned this when I built the bionic eye and used colors back in 2012 when Marak had his first issue. Started writing things on my own as much as I possibly could back then.

All we can do is try our hardest to do our best, or opt that the risk is not worth paying our own developers to write our own version instead of using something free. Also, if we like a free work but don't want the risk, if the licence says its OK, we can use it after code review in our own way, or be inspired by it when writing our own code.

This is the nature of OSS. Every coin has 2 sides, and we have to at the very least be `aware` of the sides if we are to choose to make an educated decision on global economic security. 

Please use your morals, and decide if you are OK with your company or government systems relying on free software and trusting when we still have people willing to start wars in our world.
