### ISSUE TITLE
[Controversial Opinion] Why isn't RIAEvangelist allowed to do this?

### ISSUE THREAD

**Issue by breadchris** [RIAEvangelist/node-ipc#530]
There is ZERO chance that this will be a productive conversation, but I figured I put this here to prove a point about open source software. 

While people are fixated on RIAEvangelist's intentions, this shindig, along with `faker.js` and `colors.js`, unearth the dirty underbelly of OSS. People can do what they want to code they have access to.

I am by no means saying it is morally right and that people should put malware in a widely used project. I personally find that morally wrong. But, did RIAEvangelist sign a contract saying that their freely available code, that they wrote and maintained on their own time, can not push whatever code they want to?

There is obviously a major problem with dependency management and people not vetting the code they include in their services. It is fun to pile on here and continue to make issues with derogatory remarks. I get it, its the Internet. But to blame this on an individual, who does not owe anyone anything, is ignoring the bigger picture of what is going on with software.

**Comment by waleed177** [comment]
You might say he is allowed to do this. But with power comes responsibility, ill let you complete that one.

**Comment by arunanshub** [comment]
He has all the liberty to do whatever he wants, but if his actions cause widespread damage to property, then he deserves to face the consequences.

**Comment by TacoGuyAT** [comment]
creating and sharing malware is totally not legal thing that you can do

**Comment by expeditiousRubyist** [comment]
NPM and Github both maintain terms of service indicating what you are and are not allowed to use their platforms for. One of those terms is that you may not use it to distribute malware. This is a totally reasonable set of terms, since not having this policy would make them untrustworthy places to obtain software.

Under federal law, using these services while exceeding the authorization they have provided you, in order to cause harm, is a felony. The exact law violated can be found in 18 U.S. Code § 1030 (a)(5). [You can read the text here](https://www.law.cornell.edu/uscode/text/18/1030#a_5)

**Comment by slawomir-pryczek** [comment]
No, the fact you have access to someone's else car bacause he forgot to close it, doesn't mean you're allowed to break or steal it.

Creating malware is illegal, doesn't matter what ToS you signed because there's gradation of law and these agreements are not legally binding. Racial / national / gender profiling is also not legal.

Yes, any idiot is allowed to destroy years of others work. But just after that - removing from community and criminal charges should follow. Otherwise, without trust that at least we won't be victims of some malware attack after downloading some code - the community will serve no purpose.

**Comment by breadchris** [comment]
> NPM and Github both maintain terms of service indicating what you are and are not allowed to use their platforms for. One of those terms is that you may not use it to distribute malware. This is a totally reasonable set of terms, since not having this policy would make them untrustworthy places to obtain software.

Thanks for that @expeditiousRubyist, that is a great point.

**Comment by dmitrymarchuk** [comment]
> THE SOFTWARE IS PROVIDED "AS IS"

> IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY

**Comment by PrivateGER** [comment]
> > THE SOFTWARE IS PROVIDED "AS IS"
> 
> > IN NO EVENT SHALL THE
> > AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
> > LIABILITY

not how law works

**Comment by VNdoug** [comment]
Intentionally spreading malware is a crime in most countries, yes.
