### ISSUE TITLE
ML?

### ISSUE THREAD

**Issue by michaelrgalloway** [RIAEvangelist/node-ipc#84]
From the description of this project and on npmjs.com I'm reading that this project is tackling Neural Networking and Machine learning but all I am seeing is some communication protocols. Does this project actually have some tools for applied Machine Learning or is this just a framework for IPC various protocols of communication?

**Comment by RIAEvangelist** [comment]
It was originally designed for communication between various parts of an ANN. The point was to allow easy scaling of multi process ANNs to distributed ANNs with only configuration changes instead of needing to refactor code. It also serves to allow mixed language ML and ANN communication.

Our initial ANN which spurred this was a combination of C, C++, and node.

So while ML coms were the point, it seems the community has picked up a LOT of other uses.

It is even being used in implantable medical devices, hospital document systems and a few automotive applications.

Go figure. :open_hands:

**Comment by joshuaalayon** [comment]
Be aware - this package was found to contain malware that detects its users machines purported geographical location and replaces the data from the machine if it does not like the location it detects

If you are still using this package - you may do better by locking it to an older version or, preferably, replacing it altogether along with all software maintained by the repos maintainer(s)

https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/amp/
